engines:
    duplication:
        enabled: true
        config:
            languages:
                - python
    pylint:
        enabled: true
    fixme:
        enabled: true
    ratings:
        paths:
            - "**.py"

    exclude_paths:
        - "testdata/**/*"
        - "requirements.txt
