language: python
python:
    - "3.6"
install:
    - |
        if [[ "${TRAVIS_PYTHON_VERSION}" = pypy ]]; then
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pip install -r requirements.txt
        fi
    - pip install tox-travis coveralls
script:
  - pytest

#after_success:
#    - coveralls